backend:
  name: git-gateway
  branch: main  # Substitua por 'master' se você estiver usando essa branch

media_folder: "uploads"  # Pasta para uploads de mídia
public_folder: "/uploads"  # Caminho para imagens

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"  # Pasta onde os posts são armazenados
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Conteúdo", name: "body", widget: "markdown" }
