backend:
  name: git-gateway
  branch: main  # A branch principal do seu repositório no GitHub

media_folder: "uploads"  # Onde suas imagens vão ser salvas no projeto
public_folder: "/uploads"  # Caminho público para suas imagens

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"  # Onde os posts vão ser salvos
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Conteúdo", name: "body", widget: "markdown" }
